an alternative take on Nim Wstanie Dzień
annkamsk/polishlyrics pull request #6
Opened 2023-01-12 01:03 UTC by k3rnelj

Co-authored by @mlazowik and my cider.

2023-01-12 01:18 UTC, annkamsk reviewed
Dobry tekst, ale rymy zginęły

2023-01-12 01:23 UTC, annkamsk commented
Pierwszy refren musi się też kończyć "lecz nie dziś", bo to istotnie wpływa na znaczenie tekstu

2023-01-12 01:25 UTC, annkamsk commented
Afaik również nie mówi się nigdy "laugh through THE tears". Nie wiem na ile wariacja tu przeszkadza, może nie bardzo

2023-01-12 01:28 UTC, annkamsk commented
Te dwie zwrotki Sunshine... i Women... można wziąć z tej wersji całe, tylko rym w drugim wersie trzeba poprawić

2023-01-12 01:32 UTC, annkamsk commented
Zwrotka We'll light up też okej, ale ostatnia cała do poprawy, bo nic się nie rymuje

2023-01-12 01:38 UTC, annkamsk commented
Jeśli chodzi o pierwszą zwrotkę, to podoba mi się From here and from afar i koncepcja z fruit rotten black. Ale układ rymów jest zupełnie off a tam to szczególnie ma znaczenie, bo rytm jest istotny

2023-01-12 21:30 UTC, annkamsk requested changes
Jak w komentarzach

2023-01-13 17:53 UTC, k3rnelj commented
> Dobry tekst, ale rymy zginęły

Tak. @mlazowik próbował ich bronić, a ja buknąłem że nie ma po co, i w sumie obstaję przy tym. Tak długo jak jest to śpiewalne i brzmi dobrze to dla mnie te rymy guzik wnoszą. Ale to dla mnie ofc, temat do przemyślenia raczej.

2023-01-13 17:54 UTC, k3rnelj commented
> Refren okej, ale tam _musi_ być "lecz nie dziś", bo to istotnie wpływa na znaczenie tekstu

Zgoda, ale nie wykminiliśmy niczego lepszego, zostawiliśmy jako kompromis który prawie trafia w znaczenie a brzmi sensownie przy śpiewaniu.

2023-01-13 17:55 UTC, k3rnelj commented
> Afaik również nie mówi się nigdy "laugh through THE tears". Nie wiem na ile wariacja tu przeszkadza, może nie bardzo

Tu akurat sprawa jest banalna, jeśli wiadomo które to łzy to _the_ jest nie tylko legalne, ale wręcz wskazane, a tutaj chodzi o dość konkretne w dość konkretny sposób wyciśnięte łzy.

2023-01-13 17:55 UTC, k3rnelj commented
> Te dwie zwrotki Sunshine... i Women... można wziąć z tej wersji całe, tylko rym w drugim wersie trzeba poprawić

W sprawie rymów poszło założenie jak wyżej, ale jak wykombinujemy jak je ocalić to ofc yes plz.

2023-01-13 17:56 UTC, k3rnelj commented
> Zwrotka We'll light up też okej, ale ostatnia cała do poprawy, bo nic się nie rymuje

Z ostatniej byliśmy najmniej dumni i do niej wypiliśmy najwięcej cydru, do dopracowania. W temacie rymów też jak wyżej ;)

2023-01-13 17:58 UTC, k3rnelj commented
> Jeśli chodzi o pierwszą zwrotkę, to podoba mi się From here and from afar i koncepcja z fruit rotten black. Ale układ rymów jest zupełnie off a tam to szczególnie ma znaczenie, bo rytm jest istotny

Again, rymy tam poświęciliśmy na ołtarzu śpiewalności i akurat ryytmu właśnie tośmy pilnowali mocno, tak żeby to jakoś brzmiało. In other words nie rozumiem implikacji że zepsuicie rymów psuje rytm, chętnie zostanę oświecony odnośnie.

2023-01-13 18:57 UTC, annkamsk commented
Rymy zawsze wzmacniają rytm. A to jest dosyć minimalistyczny utwór, w którym instrumentalnie czy wokalnie niewiele się dzieje, więc tekst jest dużo bardziej widoczny. Zgoda, że naturalność językowa ma większy priorytet. Ale pomyślę, jak tam się da te rymy uratować. 

> Tu akurat sprawa jest banalna, jeśli wiadomo które to łzy to the jest nie tylko legalne, ale wręcz wskazane, a tutaj chodzi o dość konkretne w dość konkretny sposób wyciśnięte łzy.

Oki, wierzę, spoko.

2023-01-13 19:02 UTC, annkamsk approved these changes
Dobra, ale to będą mniejsze poprawki w sumie. Na razie merge.

2023-01-13 19:02 UTC, merged